export const ROUTES = {
  LOGIN: 'Login',
  REGISTER: 'Register',
  VERIFY_EMAIL: 'VerifyEmail',
  FORGOT_PASSWORD: 'ForgotPassword',
  RESET_PASSWORD: 'ResetPassword',
  FEED: 'Feed',
  FEED_HOME: 'FeedHome',
  REPORT_DETAIL: 'ReportDetail',
  CREATE_REPORT: 'CreateReport',
  CONVERSATIONS: 'Conversations',
  CONVERSATIONS_LIST: 'ConversationsList',
  CHAT: 'Chat',
  PROFILE: 'Profile',
  USER_PUBLIC_PROFILE: 'UserPublicProfile',
} as const;
